version: '3.8'

services: 
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    ports: 
      - 8000:8000
    volumes: 
      - .:/code
    depends_on:
      - db
    environment: 
      - "DJANGO_SECRET_KEY=django-insecure-oie$$^!r!oq+v5^f!a+ipm&-wxl1)c5_9)v@&e_o*#)%b2!at!d"
      - "DJANGO_DEBUG=True"
  db:
    image: postgres:11
    volumes: 
      - postgres_data:/var/lib/postgresql/data/
    environment: 
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    
volumes: 
  postgres_data:

